# Generated by Django 3.0.5 on 2021-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210429_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='s4sy4T1uiw', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
