# Generated by Django 3.0.5 on 2021-04-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210429_1744'),
        ('users', '0003_auto_20210423_1522'),
    ]

    operations = [
    ]
