# Generated by Django 3.0.5 on 2021-05-05 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210504_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('cadd54ee-ad79-11eb-b2b5-6d315d54747d'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
