# Generated by Django 3.0.5 on 2021-05-04 16:49

from django.db import migrations, models
import titles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, validators=[titles.validators.year_validator], verbose_name='Год издания'),
        ),
    ]
